[package]

name = "neural"
version = "0.0.1"
authors = [ "jim@barkingmousestudio.com" ]

[dependencies]
wheel_timer = "*"
rand = "*"
vec_map = "*"
num = "*"

[dev-dependencies]
csv = "*"

[lib]

name = "neural"

[profile.bench]
opt-level = 3
